apiVersion: constraints.gatekeeper.sh/v1beta1
kind: KafkaTopicPartitionLimit
metadata:
  name: kafkatopicpartitionlimit
spec:
  match:
    kinds:
      - apiGroups: ["platform.confluent.io"]
        kinds: ["KafkaTopic"]
