apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
  namespace: confluent
spec:
  dataVolumeCapacity: 1G
  image:
    application: docker.io/confluentinc/cp-server:7.7.0
    init: confluentinc/confluent-init-container:2.9.0
  replicas: 1
  configOverrides:
    server:
    - create.topic.policy.class.name=com.confluent.csta.MyTopicPolicy
  mountedVolumes:
    volumes:
      - name: custom
        persistentVolumeClaim:
          claimName: custom-pvc  
    volumeMounts:
      - name: custom
        mountPath: /usr/ce-broker-plugins/build/libs
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  dataVolumeCapacity: 1G
  image:
    application: docker.io/confluentinc/cp-server:7.7.0
    init: confluentinc/confluent-init-container:2.9.0
  replicas: 1
  configOverrides:
    server:
    - create.topic.policy.class.name=com.confluent.csta.MyTopicPolicy
  mountedVolumes:
    volumes:
      - name: custom
        persistentVolumeClaim:
          claimName: custom-pvc  
    volumeMounts:
      - name: custom
        mountPath: /usr/ce-broker-plugins/build/libs
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: krc-cfk
  namespace: confluent
spec:
  kafkaClusterRef:
    name: kafka
  kafkaRest:
    endpoint: http://kafka.confluent.svc.cluster.local:8090
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: demotopic
  namespace: confluent
spec:
  kafkaRestClassRef:
    name: krc-cfk
  replicas: 1
  partitionCount: 4
  configs:
    cleanup.policy: "delete"