apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: righttopic
  namespace: confluent
spec:
  kafkaRestClassRef:
    name: krc-cfk
  replicas: 1
  partitionCount: 2
  configs:
    cleanup.policy: "delete"