apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: rightpartitions
  namespace: confluent
spec:
  kafkaRestClassRef:
    name: krc-cfk
  replicas: 1
  partitionCount: 4
  configs:
    cleanup.policy: "delete"