apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: wrongtopic2024
  namespace: confluent
spec:
  kafkaRestClassRef:
    name: krc-cfk
  replicas: 1
  partitionCount: 3
  configs:
    cleanup.policy: "delete"